# 智付通測試平台: https://cwww.spgateway.com/
# 信用卡測試卡號: 4000-2211-2222-2222

default: &default
  merchant_id: MS33418458
  hash_key: DEOViIHoxZRzElSe9p14KFa8k4vx7Tfv
  hash_iv: nIxiaIldrOFR4JPe
  url: https://ccore.spgateway.com/MPG/mpg_gateway
  notify_url: http://requestbin.fullcontact.com/xrzi3wxs

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

production:
  <<: *default
